# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-PayflowPro
version:      0.06
version_from: PayflowPro.pm
installdirs:  site
requires:
    Business::OnlinePayment:       0
    PFProAPI:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
